spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cats
    username: [RETRACTED]
    password: [RETRACTED]
    
